export const motivationalQuotes: string[] = [
  'The only way to do great work is to love what you do.',
  "Believe you can and you're halfway there.",
  'Success is not final, failure is not fatal: it is the courage to continue that counts.',
  'The future belongs to those who believe in the beauty of their dreams.',
  "Don't watch the clock; do what it does. Keep going.",
  'Dream big and dare to fail.',
  'Keep your eyes on the stars, and your feet on the ground.',
  'It always seems impossible until it’s done.',
  'You are never too old to set another goal or to dream a new dream.',
  'Start where you are. Use what you have. Do what you can.',
  'Hardships often prepare ordinary people for an extraordinary destiny.',
  'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.',
  'Don’t watch the clock; do what it does. Keep going.',
  'Everything you’ve ever wanted is on the other side of fear.',
  'It’s not whether you get knocked down, it’s whether you get up.',
  'You miss 100% of the shots you don’t take.',
  'The harder the battle, the sweeter the victory.',
  'Don’t limit your challenges. Challenge your limits.',
  'Success doesn’t come from what you do occasionally, it comes from what you do consistently.',
  'The secret of getting ahead is getting started.',
  'The best way to predict the future is to create it.',
  'Your limitation—it’s only your imagination.',
  'Push yourself, because no one else is going to do it for you.',
  'Great things never come from comfort zones.',
  'Dream it. Wish it. Do it.',
  'Success doesn’t just find you. You have to go out and get it.',
  'The harder you work for something, the greater you’ll feel when you achieve it.',
  'Dream bigger. Do bigger.',
  'Don’t stop when you’re tired. Stop when you’re done.',
  'Wake up with determination. Go to bed with satisfaction.',
  'Do something today that your future self will thank you for.',
  'Little things make big days.',
  'It’s going to be hard, but hard does not mean impossible.',
  'Don’t wait for opportunity. Create it.',
  'Sometimes we’re tested not to show our weaknesses, but to discover our strengths.',
  'The key to success is to focus on goals, not obstacles.',
  'Dream it. Believe it. Build it.',
];
